### ISSUE TITLE
corrupt tiles.cpp

### ISSUE THREAD

**Issue by neozeed** [binji/simfun#1]
I just tried to build on Windows and noticed that line 186 of tiles.cpp is corrupt, it's missing the t;

		/* 63 degree high DL, DR, UL, UR */
		Tile

minor thing to fix, and runs on MinGW32 with GCC 7

I had to add -fpermissive to the build but otherwise no problem!

gcc -fpermissive -ISDL -I../include -c *.cpp
gcc -c -ISDL SDL_win32_main.c
gcc *.o -lmingw32 -mwin32 -static-libgcc -lSDL -static-libstdc++ -lstdc++ -lopengl32  -lglu32

**Comment by binji** [comment]
Ha, nice! I wrote this a long time ago, and never really tried to compile it I guess. Cool that it still works though!

**Comment by neozeed** [comment]
Although I've never played it before but it does run on Windows!  I haven't tried anything else but that minor thing would have held them all back.   Did you ever use it for anything?  It looks like it's got all the basics in for a fun platformer!

**Comment by binji** [comment]
Funny enough, this was a programming test for my first job! So I only made enough to pass the test 😁
